name: devotee
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^2.0.10+1
  animated_custom_dropdown: ^3.1.1
  flutter_floating_bottom_bar: ^1.2.0
  stylish_bottom_bar: ^1.1.0
  http: ^1.1.0
  sms_autofill: ^2.4.0
  permission_handler: ^11.0.1
  otp_text_field: ^1.1.3
  telephony: ^0.2.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  fragment_navigate: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.14.0
  cached_network_image: ^3.3.1
  firebase_storage: ^11.6.0
  emoji_picker_flutter: ^1.6.4
  firebase_messaging: ^14.7.10
  googleapis_auth: ^1.4.1
  gallery_saver_updated: ^3.0.0
  lottie: ^2.6.0
  google_generative_ai: ^0.4.1
  intl: ^0.19.0
  multi_image_picker2: ^5.0.02
  awesome_dialog: ^3.2.1
  restart_app: ^1.2.1
  carousel_slider: ^5.0.0
  dropdown_search: ^5.0.6
  flutter_notification_channel: ^2.0.0
  image_cropper: ^5.0.1
  firebase_database: ^10.4.0
  share_plus: ^7.2.2
  badges: ^3.1.2
  flutter_local_notifications: ^17.2.3
  rxdart: ^0.27.7
  flutter_app_badger: ^1.5.0
  flutter_windowmanager: ^0.2.0
  youtube_player_flutter: ^8.0.0
  connectivity_plus: ^5.0.2
  firebase_analytics: ^10.8.0
  dotted_border: ^2.1.0
  photo_view: ^0.15.0
  flutter_launcher_icons: ^0.13.1
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.1.14
  just_audio: ^0.9.37
  audio_video_progress_bar: 2.0.2
  video_player: ^2.7.2
  # audio_service: ^0.18.15
  just_audio_background: ^0.0.1-beta.13

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Medium.ttf
        - asset: fonts/poppins/Poppins-SemiBold.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
    - family: Gabriela
      fonts:
        - asset: fonts/poppins/Gabriela-Regular.ttf

plugin:
  platforms:
    android:
      package: audio_service
      pluginClass: AudioServicePlugin

